// src/components/LoginModal.vue
<script setup>
/**
 * LoginModal.vue
 * Modal con dos tabs: Ingresar y Registrarse.
 *
 * Props:   open (Boolean)
 * Emits:   close
 *
 * Usa el store de auth para login.
 * Usa authApi.register para el registro.
 */
import { ref, watch } from 'vue'
import { X, Eye, EyeOff, Loader2 } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth'
import { authApi } from '@/api/axios'
import { useToast } from 'vue-toastification'

const props = defineProps({ open: Boolean })
const emit  = defineEmits(['close'])

const auth  = useAuthStore()
const toast = useToast()

// ── Estado local ──────────────────────────
const tab      = ref('login')   // 'login' | 'register'
const showPass = ref(false)
const loading  = ref(false)

// Formulario unificado: se usan los campos según el tab
const form = ref({
  numero_id:        '',
  password:         '',
  confirm_password: '',
  nombre:           '',
  tipo_id:          'CC',
})

// Resetear al abrir el modal
watch(() => props.open, (val) => {
  if (val) { tab.value = 'login'; Object.keys(form.value).forEach(k => { form.value[k] = k === 'tipo_id' ? 'CC' : '' }) }
})

// ── Login ─────────────────────────────────
async function handleLogin() {
  loading.value = true
  try {
    await auth.login(form.value.numero_id, form.value.password)
    toast.success('¡Bienvenido de nuevo!')
    emit('close')
  } catch {
    toast.error('Número de identificación o contraseña incorrectos')
  } finally { loading.value = false }
}

// ── Registro ──────────────────────────────
async function handleRegister() {
  if (form.value.password !== form.value.confirm_password) {
    toast.warning('Las contraseñas no coinciden'); return
  }
  loading.value = true
  try {
    await authApi.register({
      numero_id:        form.value.numero_id,
      password:         form.value.password,
      confirm_password: form.value.confirm_password,
      nombre:           form.value.nombre,
      tipo_id:          form.value.tipo_id,
    })
    toast.success('Cuenta creada. Ahora puedes ingresar.')
    tab.value = 'login'
  } catch (err) {
    const data = err.response?.data
    const msg  = data ? Object.values(data).flat().join(' · ') : 'Error al registrarse'
    toast.error(msg)
  } finally { loading.value = false }
}
</script>

<template>
  <!-- Overlay -->
  <Transition name="modal">
    <div v-if="open"
         class="fixed inset-0 z-[9999] flex items-center justify-center p-4"
         style="background:rgba(0,0,0,0.75);backdrop-filter:blur(8px)"
         @click.self="$emit('close')">

      <!-- Panel -->
      <div class="w-full max-w-md bg-card border border-border rounded-xl overflow-hidden shadow-[0_24px_80px_rgba(0,0,0,0.6)]">

        <!-- Encabezado -->
        <div class="flex justify-between items-start p-6 pb-0">
          <div>
            <h2 class="font-head font-extrabold text-2xl tracking-tight">
              {{ tab === 'login' ? 'Bienvenido' : 'Crear cuenta' }}
            </h2>
            <p class="text-t-secondary text-sm mt-1">
              {{ tab === 'login' ? 'Ingresa para reservar tu espacio' : 'Regístrate y comienza a reservar' }}
            </p>
          </div>
          <button class="p-1.5 rounded-sm bg-input border border-border text-t-secondary hover:text-t-primary transition-colors"
                  @click="$emit('close')">
            <X :size="15" />
          </button>
        </div>

        <!-- Tabs -->
        <div class="flex gap-1 mx-6 mt-5 p-1 bg-input rounded-sm">
          <button :class="['flex-1 py-2 rounded text-xs font-semibold transition-all',
                           tab === 'login' ? 'bg-card text-t-primary shadow' : 'text-t-muted']"
                  @click="tab = 'login'">Ingresar</button>
          <button :class="['flex-1 py-2 rounded text-xs font-semibold transition-all',
                           tab === 'register' ? 'bg-card text-t-primary shadow' : 'text-t-muted']"
                  @click="tab = 'register'">Registrarse</button>
        </div>

        <!-- Cuerpo -->
        <div class="p-6">

          <!-- ─── Formulario Login ─── -->
          <form v-if="tab === 'login'" @submit.prevent="handleLogin" class="flex flex-col gap-4">
            <div>
              <label class="label-dark block mb-1.5">N° IDENTIFICACIÓN</label>
              <input class="input-dark" v-model="form.numero_id" placeholder="Ej: 1234567890" required />
            </div>
            <div>
              <label class="label-dark block mb-1.5">CONTRASEÑA</label>
              <div class="relative">
                <input class="input-dark pr-10"
                       :type="showPass ? 'text' : 'password'"
                       v-model="form.password" required />
                <button type="button"
                        class="absolute right-3 top-1/2 -translate-y-1/2 text-t-muted hover:text-t-secondary transition-colors"
                        @click="showPass = !showPass">
                  <EyeOff v-if="showPass" :size="15" />
                  <Eye v-else :size="15" />
                </button>
              </div>
            </div>
            <button type="submit" class="btn-primary w-full justify-center py-3 mt-1" :disabled="loading">
              <Loader2 v-if="loading" :size="15" class="animate-spin" />
              <span v-else>Ingresar →</span>
            </button>
          </form>

          <!-- ─── Formulario Registro ─── -->
          <form v-else @submit.prevent="handleRegister" class="flex flex-col gap-3.5">
            <div class="grid grid-cols-2 gap-3">
              <div>
                <label class="label-dark block mb-1.5">TIPO ID</label>
                <select class="input-dark" v-model="form.tipo_id">
                  <option value="CC">Cédula (CC)</option>
                  <option value="TI">T. Identidad (TI)</option>
                  <option value="CE">C. Extranjería</option>
                  <option value="PPT">PPT</option>
                </select>
              </div>
              <div>
                <label class="label-dark block mb-1.5">N° IDENTIFICACIÓN</label>
                <input class="input-dark" v-model="form.numero_id" placeholder="1234567890" required />
              </div>
            </div>
            <div>
              <label class="label-dark block mb-1.5">NOMBRE COMPLETO</label>
              <input class="input-dark" v-model="form.nombre" placeholder="Tu nombre completo" required />
            </div>
            <div>
              <label class="label-dark block mb-1.5">CONTRASEÑA</label>
              <div class="relative">
                <input class="input-dark pr-10"
                       :type="showPass ? 'text' : 'password'"
                       v-model="form.password" required />
                <button type="button"
                        class="absolute right-3 top-1/2 -translate-y-1/2 text-t-muted hover:text-t-secondary"
                        @click="showPass = !showPass">
                  <EyeOff v-if="showPass" :size="15" />
                  <Eye v-else :size="15" />
                </button>
              </div>
            </div>
            <div>
              <label class="label-dark block mb-1.5">CONFIRMAR CONTRASEÑA</label>
              <input class="input-dark" type="password" v-model="form.confirm_password" required />
            </div>
            <button type="submit" class="btn-primary w-full justify-center py-3 mt-1" :disabled="loading">
              <Loader2 v-if="loading" :size="15" class="animate-spin" />
              <span v-else>Crear cuenta →</span>
            </button>
          </form>

        </div>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.modal-enter-active, .modal-leave-active { transition: opacity .2s, transform .2s; }
.modal-enter-from, .modal-leave-to { opacity: 0; transform: scale(0.95) translateY(12px); }
</style>

// src/components/LoginModal.jsx
import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Eye, EyeOff, Loader2 } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { authApi } from '../api/axios'
import { toast } from 'react-toastify'

const S = {
  overlay: {
    position: 'fixed', inset: 0, zIndex: 1000,
    background: 'rgba(0,0,0,0.75)',
    backdropFilter: 'blur(8px)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    padding: '1rem',
  },
  modal: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-xl)',
    width: '100%', maxWidth: 420,
    overflow: 'hidden',
    boxShadow: '0 24px 80px rgba(0,0,0,0.6)',
  },
  header: {
    padding: '1.5rem 1.5rem 0',
    display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
  },
  title: {
    fontFamily: 'var(--font-head)', fontWeight: 800, fontSize: 24,
    color: 'var(--text-primary)', letterSpacing: '-0.5px',
  },
  subtitle: { fontSize: 13, color: 'var(--text-secondary)', marginTop: 4 },
  closeBtn: {
    background: 'var(--bg-input)', border: '1px solid var(--border)',
    borderRadius: 8, padding: 6, cursor: 'pointer',
    color: 'var(--text-secondary)', display: 'flex',
  },
  tabs: {
    display: 'flex', gap: 4, margin: '1.25rem 1.5rem 0',
    background: 'var(--bg-input)', borderRadius: 'var(--radius-sm)',
    padding: 4,
  },
  tab: (active) => ({
    flex: 1, padding: '8px 0', border: 'none', cursor: 'pointer',
    borderRadius: 6, fontSize: 13, fontWeight: 600,
    background: active ? 'var(--bg-card)' : 'transparent',
    color: active ? 'var(--text-primary)' : 'var(--text-muted)',
    boxShadow: active ? '0 1px 6px rgba(0,0,0,0.3)' : 'none',
    transition: 'all .2s',
  }),
  body: { padding: '1.25rem 1.5rem 1.5rem' },
  group: { display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 14 },
  label: { fontSize: 12, fontWeight: 500, color: 'var(--text-secondary)', letterSpacing: '0.04em' },
  inputWrap: { position: 'relative' },
  input: {
    width: '100%', padding: '10px 14px',
    background: 'var(--bg-input)', border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)', color: 'var(--text-primary)',
    fontSize: 14, outline: 'none', transition: 'border .2s',
    fontFamily: 'var(--font-body)',
  },
  eyeBtn: {
    position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)',
    background: 'none', border: 'none', cursor: 'pointer',
    color: 'var(--text-muted)', padding: 0, display: 'flex',
  },
  submitBtn: {
    width: '100%', padding: '11px',
    background: 'var(--accent)', border: 'none',
    borderRadius: 'var(--radius-sm)', color: '#000',
    fontFamily: 'var(--font-head)', fontWeight: 700, fontSize: 15,
    cursor: 'pointer', display: 'flex', alignItems: 'center',
    justifyContent: 'center', gap: 8, marginTop: 8,
    transition: 'opacity .2s',
  },
  divider: {
    display: 'flex', alignItems: 'center', gap: 10,
    color: 'var(--text-muted)', fontSize: 12, margin: '14px 0',
  },
  line: { flex: 1, height: 1, background: 'var(--border)' },
}

export default function LoginModal({ open, onClose }) {
  const { login } = useAuth()
  const [tab, setTab] = useState('login') // 'login' | 'register'
  const [showPass, setShowPass] = useState(false)
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({
    numero_id: '', password: '', nombre: '',
    tipo_id: 'CC', confirm_password: '',
  })

  const set = (k) => (e) => setForm(f => ({ ...f, [k]: e.target.value }))

  const handleLogin = async (e) => {
    e.preventDefault()
    setLoading(true)
    try {
      await login(form.numero_id, form.password)
      toast.success('¡Bienvenido de nuevo!')
      onClose()
    } catch {
      toast.error('Credenciales incorrectas')
    } finally { setLoading(false) }
  }

  const handleRegister = async (e) => {
    e.preventDefault()
    if (form.password !== form.confirm_password) {
      toast.warning('Las contraseñas no coinciden')
      return
    }
    setLoading(true)
    try {
      await authApi.register(form)
      toast.success('Cuenta creada. Ya puedes ingresar.')
      setTab('login')
    } catch (err) {
      const msg = err.response?.data ? JSON.stringify(err.response.data) : 'Error al registrarse'
      toast.error(msg)
    } finally { setLoading(false) }
  }

  if (!open) return null

  return (
    <AnimatePresence>
      <motion.div
        style={S.overlay}
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
        onClick={(e) => e.target === e.currentTarget && onClose()}
      >
        <motion.div
          style={S.modal}
          initial={{ scale: 0.9, y: 20 }} animate={{ scale: 1, y: 0 }}
          exit={{ scale: 0.9, y: 20 }}
          transition={{ type: 'spring', stiffness: 280, damping: 24 }}
        >
          <div style={S.header}>
            <div>
              <div style={S.title}>{tab === 'login' ? 'Bienvenido' : 'Crear cuenta'}</div>
              <div style={S.subtitle}>
                {tab === 'login' ? 'Ingresa para reservar tu espacio' : 'Regístrate y empieza a reservar'}
              </div>
            </div>
            <button style={S.closeBtn} onClick={onClose}><X size={16} /></button>
          </div>

          {/* Tabs */}
          <div style={S.tabs}>
            <button style={S.tab(tab === 'login')} onClick={() => setTab('login')}>Ingresar</button>
            <button style={S.tab(tab === 'register')} onClick={() => setTab('register')}>Registrarse</button>
          </div>

          <div style={S.body}>
            {tab === 'login' ? (
              <form onSubmit={handleLogin}>
                <div style={S.group}>
                  <label style={S.label}>N° IDENTIFICACIÓN</label>
                  <input style={S.input} value={form.numero_id} onChange={set('numero_id')}
                    placeholder="Ej: 1234567890" required />
                </div>
                <div style={S.group}>
                  <label style={S.label}>CONTRASEÑA</label>
                  <div style={S.inputWrap}>
                    <input style={{ ...S.input, paddingRight: 40 }}
                      type={showPass ? 'text' : 'password'}
                      value={form.password} onChange={set('password')} required />
                    <button type="button" style={S.eyeBtn} onClick={() => setShowPass(p => !p)}>
                      {showPass ? <EyeOff size={16} /> : <Eye size={16} />}
                    </button>
                  </div>
                </div>
                <button style={S.submitBtn} disabled={loading}>
                  {loading ? <Loader2 size={16} className="spin" /> : 'Ingresar'}
                </button>
              </form>
            ) : (
              <form onSubmit={handleRegister}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0 12px' }}>
                  <div style={S.group}>
                    <label style={S.label}>TIPO ID</label>
                    <select style={S.input} value={form.tipo_id} onChange={set('tipo_id')}>
                      <option value="CC">Cédula (CC)</option>
                      <option value="TI">T. Identidad (TI)</option>
                      <option value="CE">C. Extranjería (CE)</option>
                      <option value="PPT">PPT</option>
                    </select>
                  </div>
                  <div style={S.group}>
                    <label style={S.label}>N° IDENTIFICACIÓN</label>
                    <input style={S.input} value={form.numero_id} onChange={set('numero_id')}
                      placeholder="1234567890" required />
                  </div>
                </div>
                <div style={S.group}>
                  <label style={S.label}>NOMBRE COMPLETO</label>
                  <input style={S.input} value={form.nombre} onChange={set('nombre')}
                    placeholder="Tu nombre" required />
                </div>
                <div style={S.group}>
                  <label style={S.label}>CONTRASEÑA</label>
                  <div style={S.inputWrap}>
                    <input style={{ ...S.input, paddingRight: 40 }}
                      type={showPass ? 'text' : 'password'}
                      value={form.password} onChange={set('password')} required />
                    <button type="button" style={S.eyeBtn} onClick={() => setShowPass(p => !p)}>
                      {showPass ? <EyeOff size={16} /> : <Eye size={16} />}
                    </button>
                  </div>
                </div>
                <div style={S.group}>
                  <label style={S.label}>CONFIRMAR CONTRASEÑA</label>
                  <input style={S.input} type="password" value={form.confirm_password}
                    onChange={set('confirm_password')} required />
                </div>
                <button style={S.submitBtn} disabled={loading}>
                  {loading ? <Loader2 size={16} /> : 'Crear cuenta'}
                </button>
              </form>
            )}
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  )
}
